#
#             へ  ♡       
#         ૮ >  <) 
#         / ⁻ ៸|         Vesktop Special Workspace                                                                            
#      乀(ˍ,ل ل   
#
# ---------------------------------------------------------------------------------
#

$class = vesktop
exec-once = vesktop

windowrule = workspace special:$class silent, match:class $class
windowrule = fullscreen 1, match:class $class
windowrule = suppress_event fullscreen, match:class $class
windowrule = workspace previous, match:workspace special:$class, match:class negative:$class

bind = $mainMod SHIFT, D, togglespecialworkspace, $class
animation = specialWorkspace, 1, 4, easeOutQuint, slidevert