# 
# ⠀⠀⠀⠀⠀⠀⢀⣿⡀⠀⠀⠀⠀⠀⠀⠀⠀
# ⠀⠀⠀⠀⠀⢀⣾⣿⡇⠀⠀⠀⠀⠀⢀⣼⡇
# ⠀⠀⠀⠀⠀⣸⣿⣿⡇⠀⠀⠀⠀⣴⣿⣿⠃
# ⠀⠀⠀⠀⢠⣿⣿⣿⣇⠀⠀⢀⣾⣿⣿⣿⠀
# ⠀⠀⠀⣴⣿⣿⣿⣿⣿⣿⣷⣿⣿⣿⣿⡟⠀        Welcome to SirQuacksALot's Hyprland
# ⠀⠀⢰⡿⠉⠀⡜⣿⣿⣿⡿⠿⢿⣿⣿⠃⠀                   Configuration
# ⠒⠒⠸⣿⣄⡘⣃⣿⣿⡟⢰⠃⠀⢹⣿⡇⠀
# ⠚⠉⠀⠈⠻⣿⣿⣿⣿⣿⣮⣤⣤⣿⡟⠁⠀
# ⠀⠀⠀⠀⠀⠀⠈⠙⠛⠛⠛⠛⠛⠁⠀⠒⠤
# ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠑⠀⠀
# ---------------------------------------------------------------------------------
#
# Wiki: https://wiki.hypr.land/Configuring/
#

# -----------------------------------------------------------
# Bases source configs
#
# The following configs are settings for general an sytem
# based settings.
#

source = ~/.config/hypr/modules/display-settings.conf
source = ~/.config/hypr/modules/env-vars.conf
source = ~/.config/hypr/modules/programs.conf
source = ~/.config/hypr/modules/auto-start.conf
source = ~/.config/hypr/modules/input-devices.conf
source = ~/.config/hypr/modules/permissions.conf

# -----------------------------------------------------------
# Look, feel and control configs
#
# These files load configurations for the look and feel
# of working in this hyprland environment.
#

source = ~/.config/hypr/modules/key-binds.conf
source = ~/.config/hypr/modules/style.conf
source = ~/.config/hypr/modules/window-rules.conf

# -----------------------------------------------------------
# Special Workspaces
#
# Add pre defined special workspace applications here.
#

source = ~/.config/hypr/modules/special-workspaces/vesktop.conf
source = ~/.config/hypr/modules/special-workspaces/zen-browser.conf
