#
#             へ  ♡       
#         ૮ >  <) 
#         / ⁻ ៸|         Auto start configurations                                                                             
#      乀(ˍ,ل ل   
#
# ---------------------------------------------------------------------------------
#
# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:
#

# Pass session instance informations
exec-once = systemctl --user import-environment HYPRLAND_INSTANCE_SIGNATURE WAYLAND_DISPLAY XDG_RUNTIME_DIR DISPLAY DBUS_SESSION_BUS_ADDRESS

# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox
exec-once = systemctl --user start hyprpolkitagent
exec-once = hyprpaper
# exec-once = ~/.config/waybar/launch.sh
exec-once = systemctl --user import-environment WAYLAND_DISPLAY HYPRLAND_INSTANCE_SIGNATURE
exec-once = sleep 1 & hyprpm reload

# reload führt zu crashes
# exec-once = ~/.config/waybar/reload.sh

# auto-resize funktioniert nicht - aktuell
# exec-once = ~/.config/waybar/auto-resize.sh &

# More complex auto starts
exec-once = ~/.config/hypr/autostart.sh

# Apply Themeing
#for libadwaita gtk4 apps you can use this command:
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"   # for GTK4 apps
#for gtk3 apps you need to install adw-gtk3 theme (in arch linux sudo pacman -S adw-gtk-theme)
exec = gsettings set org.gnome.desktop.interface gtk-theme "adw-gtk3"   # for GTK3 apps

# Hyprland Monitor Manager - Auto-manage displays and lid
exec-once = hmonitor daemon

# Tab menu
exec-once = snappy-switcher --daemon